spring:
  r2dbc:
    url: r2dbc:h2:mem:///test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE # H2 데이터베이스 URL
  h2:
    console:
      enabled: true
      path: h2-console
  sql:
    init:
      data-locations: initdata.sql
      schema-locations: schema.sql
      mode: always
  devtools:
    livereload:
      enabled: false

#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
server:
  port: 8080

logging:
  level:
    root: info
