spring:
  r2dbc:
    url: r2dbc:h2:mem:///test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  h2:
    console:
      path: h2-console
      enabled: true

  sql:
    init:
      data-locations: initdata.sql
      schema-locations: schema.sql
      mode: always
  devtools:
    livereload:
      enabled: false

webclient.h2-console-port: 8081

#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
server:
  port: 8080

logging:
  level:
    root: info
