spring:
  datasource:
    url: jdbc:h2:mem:~/lotte/seat-reservation/h2-console;
    driver-class-name: org.h2.Driver
  r2dbc:
    url: r2dbc:h2:mem:~/lotte/seat-reservation/h2-console;
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    defer-datasource-initialization: true
  mvc:
    hidden method:
      filter:
        enabled: true
  sql:
    init:
      platform: h2
      data-locations: classpath:initdata.sql
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
server:
  port: 8080